(source "melpa" "http://melpa.milkbox.net/packages/")
(source "gnu" "http://elpa.gnu.org/packages/")
(source "elpa" "http://tromey.com/elpa/")
(source "marmalade" "http://marmalade-repo.org/packages/")

(depends-on "auto-complete")
(depends-on "auto-complete-clang-async")
(depends-on "autopair")
(depends-on "cask")
(depends-on "cmake-project")
(depends-on "color-theme")
(depends-on "color-theme-sanityinc-solarized")
(depends-on "color-theme-solarized")
(depends-on "dash")
(depends-on "epl")
(depends-on "f")
(depends-on "flymake-cursor")
(depends-on "google-c-style")
(depends-on "magit")
(depends-on "pallet")
(depends-on "popup")
(depends-on "s")
(depends-on "yasnippet")